name: ngfront-prod
services:
  ngfront-prod:
    image: ngfront-prod
    build:
      context: ..
      dockerfile: production/Dockerfile
    container_name: ngfront-prod
    restart: always
    volumes:
      - ./config.json:/usr/share/nginx/html/assets/config.json:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "14280:80"